package lacar.junilu.aoc2024.day08

import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test

class Day08Test {
    @Test
    fun `Example Part 1`() {
        assertEquals(14, puzzleUsingExample.part1())
    }

    companion object {
        val example = """
            ............
            ........0...
            .....0......
            .......0....
            ....0.......
            ......A.....
            ............
            ............
            ........A...
            .........A..
            ............
            ............
            """.trimIndent().lines()

        var puzzleUsingExample = Day08.using(example)
    }
}