package lacar.junilu.aoc2024.day06

import lacar.junilu.experimental.Puzzle
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test

class Day06Test {
    @Test
    fun `Example - Part 1`() {
        assertEquals(41, usingExample.solve(Day06.part1))
        assertEquals(41, usingExample.solve(Day06GptDebugged.part1))
    }

    @Test
    fun `Solution - Part 1`() {
        assertEquals(4665, usingInputForGitHub.solve(Day06.part1))
        assertEquals(4656, usingInputForGmail.solve(Day06.part1))
    }

    @Test
    fun `Solution - Part 1 generated by ChatGpt with corrections`() {
        assertEquals(4665, usingInputForGitHub.solve(Day06GptDebugged.part1))
        assertEquals(4656, usingInputForGmail.solve(Day06GptDebugged.part1))
    }

    @Test
    fun `Example - Part 2`() {
        assertEquals(6, usingDebuggingInput.solve(Day06.part2))
    }

    @Test
    fun `Solution - Part 2 generated by ChatGpt with corrections`() {
        assertEquals(1688, usingInputForGitHub.solve(Day06Gpt.part2))
    }

    companion object {
        val usingInputForGitHub = Puzzle.using("aoc2024/day06-gh")
        val usingInputForGmail = Puzzle.using("aoc2024/day06-gm")

        val debuggingInput = """
            ....#.....
            .........#
            ..........
            ..#.......
            .......#..
            ..........
            .#..^.....
            ........#.
            #.........
            ......#...
            """.trimIndent()

        val usingDebuggingInput = Puzzle.usingText(debuggingInput)

        val exampleInput = """
            ....#.....
            .........#
            ..........
            ..#.......
            .......#..
            ..........
            .#..^.....
            ........#.
            #.........
            ......#...
            """.trimIndent()

        val usingExample = Puzzle.usingText(exampleInput)

    }
}