package lacar.junilu.aoc2025.day07

import lacar.junilu.readPuzzleInput
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test

class Day07Test {
    @Test
    fun `GitHub input solutions`() {
        val puzzle = Day07(readPuzzleInput("aoc2025/day07-gh"))

        assertEquals(1566, puzzle.beamSplits())
        assertEquals(0, puzzle.beamTimeLines())
    }

    @Test
    fun `Example `() {
        val example = Day07(
            """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............""".trimIndent().lines())

        assertEquals(21, example.beamSplits())
        assertEquals(40, example.beamTimeLines())
    }
}

